#include "ui/fonts.hpp"

#include <algorithm>
#include <string_view>

#include "slopkit_notosans_regular.h"
#include "slopkit_notosansmono_regular.h"

namespace slopkit::ui
{
    namespace
    {
        // Cached for ui_font()/mono_font(); refreshed by load_embedded_fonts().
        ImFont* g_ui_font   = nullptr;
        ImFont* g_mono_font = nullptr;

        // Copies a short name into ImFontConfig's fixed-size Name buffer.
        void set_font_name(ImFontConfig& config, std::string_view name)
        {
            std::ranges::copy(name, config.Name);
        }
    } // namespace

    bool load_embedded_fonts(float base_size)
    {
        ImGuiIO& io = ImGui::GetIO();

        ImFontConfig ui_config;
        // The generated byte arrays are static; ImGui must not free them.
        ui_config.FontDataOwnedByAtlas = false;
        ui_config.OversampleH          = 2;
        ui_config.OversampleV          = 1;
        ui_config.PixelSnapH           = true;

        auto*      ui_data      = const_cast<unsigned char*>(slopkit::generated::slopkit_notosans_regular);
        const auto ui_data_size = static_cast<int>(slopkit::generated::slopkit_notosans_regular_size);
        g_ui_font               = io.Fonts->AddFontFromMemoryTTF(ui_data, ui_data_size, base_size, &ui_config);

        ImFontConfig mono_config;
        mono_config.FontDataOwnedByAtlas = false;
        // A fixed-width face must not be pixel-snapped or glyphs drift off-pitch.
        mono_config.PixelSnapH           = false;
        set_font_name(mono_config, "slopkit-mono");

        auto*      mono_data      = const_cast<unsigned char*>(slopkit::generated::slopkit_notosansmono_regular);
        const auto mono_data_size = static_cast<int>(slopkit::generated::slopkit_notosansmono_regular_size);
        g_mono_font               = io.Fonts->AddFontFromMemoryTTF(mono_data, mono_data_size, base_size, &mono_config);

        return g_ui_font != nullptr && g_mono_font != nullptr;
    }

    ImFont* ui_font()
    {
        return g_ui_font;
    }

    ImFont* mono_font()
    {
        return g_mono_font;
    }

    ScopedMonoFont::ScopedMonoFont()
    {
        if (g_mono_font == nullptr)
        {
            return;
        }

        ImGui::PushFont(g_mono_font);
        pushed_ = true;
    }

    ScopedMonoFont::~ScopedMonoFont()
    {
        if (pushed_)
        {
            ImGui::PopFont();
        }
    }

    void apply_font_scale(float scale)
    {
        ImGui::GetStyle().FontScaleDpi = scale;
    }

} // namespace slopkit::ui
