#include "ui/fonts.hpp"

#include "slopkit_notosans_regular.h"

namespace slopkit::ui
{

    ImFont* load_embedded_font(float base_size)
    {
        ImGuiIO& io = ImGui::GetIO();

        ImFontConfig config;
        // The generated byte array is static; ImGui must not free it.
        config.FontDataOwnedByAtlas = false;
        config.OversampleH          = 2;
        config.OversampleV          = 1;
        config.PixelSnapH           = true;

        auto*      data      = const_cast<unsigned char*>(slopkit::generated::slopkit_notosans_regular);
        const auto data_size = static_cast<int>(slopkit::generated::slopkit_notosans_regular_size);
        return io.Fonts->AddFontFromMemoryTTF(data, data_size, base_size, &config);
    }

    void apply_font_scale(float scale)
    {
        ImGui::GetStyle().FontScaleDpi = scale;
    }

} // namespace slopkit::ui
