# Embeds a binary file into a generated C++ header.
#
#   embed_font(<target> <font_path> <symbol_name>)
#
# Writes ${CMAKE_BINARY_DIR}/generated/<symbol_name>.h containing
#   inline constexpr unsigned char <symbol_name>[]
#   inline constexpr unsigned long <symbol_name>_size
# then adds the generated include directory to <target>. The generation is
# re-run whenever <font_path> changes.

function(embed_font target font_path symbol_name)
    if(NOT EXISTS "${font_path}")
        message(FATAL_ERROR "embed_font: no such file: ${font_path}")
    endif()

    file(READ "${font_path}" font_hex HEX)
    string(LENGTH "${font_hex}" font_hex_length)
    math(EXPR font_byte_length "${font_hex_length} / 2")

    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," font_bytes "${font_hex}")
    string(REGEX REPLACE ",$" "" font_bytes "${font_bytes}")

    set(generated_dir "${CMAKE_BINARY_DIR}/generated")
    set(generated_header "${generated_dir}/${symbol_name}.h")
    file(WRITE "${generated_header}"
"// Generated by cmake/EmbedFont.cmake from ${font_path}. Do not edit.
#pragma once

namespace slopkit::generated
{

    inline constexpr unsigned char ${symbol_name}[] = { ${font_bytes} };

    inline constexpr unsigned long ${symbol_name}_size = ${font_byte_length}ul;

} // namespace slopkit::generated
")

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${font_path}")

    get_target_property(target_type ${target} TYPE)
    if(target_type STREQUAL "INTERFACE_LIBRARY")
        target_include_directories(${target} INTERFACE "${generated_dir}")
    else()
        target_include_directories(${target} PUBLIC "${generated_dir}")
    endif()
endfunction(embed_font)
