# Program icon pipeline: turns the single source image into the installed
# hicolor PNG set and into an embedded RGBA8 blob for the window icon.
#
#   slopkit_icon_pngs(<jpg> <out_var> [SIZES 16 24 ...])
#     Writes ${CMAKE_BINARY_DIR}/icons/<N>x<N>/apps/slopkit.png for every size
#     and returns the resulting file list in <out_var>.
#
#   embed_window_icon(<target> <jpg> <size> <symbol>)
#     Writes ${CMAKE_BINARY_DIR}/generated/<symbol>.h containing
#       inline constexpr unsigned char <symbol>[]        (size*size*4 bytes)
#       inline constexpr unsigned long <symbol>_width
#       inline constexpr unsigned long <symbol>_height
#     then adds the generated include directory to <target>.
#
# Both functions require SLOPKIT_MAGICK_EXECUTABLE (resolved in CMakeLists.txt)
# and re-run whenever <jpg> changes.

# Geometry of the icon square inside data/icon.jpg (1408x768 source): the dark
# rounded-square body measures 640x639+384+73, so this crop keeps a clean square
# with an even border. Override when the source layout changes.
set(SLOPKIT_ICON_CROP "640x640+384+64" CACHE STRING "Crop geometry applied to the program icon source")

function(slopkit_icon_pngs jpg out_var)
    cmake_parse_arguments(ARG "" "" "SIZES" ${ARGN})

    if(NOT EXISTS "${jpg}")
        message(FATAL_ERROR "slopkit_icon_pngs: no such file: ${jpg}")
    endif()

    set(pngs "")
    foreach(size IN LISTS ARG_SIZES)
        set(png_dir "${CMAKE_BINARY_DIR}/icons/${size}x${size}/apps")
        set(png_path "${png_dir}/slopkit.png")
        file(MAKE_DIRECTORY "${png_dir}")
        execute_process(
            COMMAND "${SLOPKIT_MAGICK_EXECUTABLE}" "${jpg}"
                    -crop "${SLOPKIT_ICON_CROP}" +repage
                    -resize "${size}x${size}"
                    -strip "${png_path}"
            COMMAND_ERROR_IS_FATAL ANY)
        list(APPEND pngs "${png_path}")
    endforeach()

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${jpg}")
    set(${out_var} "${pngs}" PARENT_SCOPE)
endfunction(slopkit_icon_pngs)

function(embed_window_icon target jpg size symbol)
    if(NOT EXISTS "${jpg}")
        message(FATAL_ERROR "embed_window_icon: no such file: ${jpg}")
    endif()

    set(generated_dir "${CMAKE_BINARY_DIR}/generated")
    file(MAKE_DIRECTORY "${generated_dir}")

    # A raw, headerless RGBA8 stream of exactly size*size*4 bytes.
    set(rgba_path "${generated_dir}/${symbol}.rgba")
    execute_process(
        COMMAND "${SLOPKIT_MAGICK_EXECUTABLE}" "${jpg}"
                -crop "${SLOPKIT_ICON_CROP}" +repage
                -resize "${size}x${size}"
                -depth 8 "rgba:${rgba_path}"
        COMMAND_ERROR_IS_FATAL ANY)

    file(READ "${rgba_path}" icon_hex HEX)
    string(LENGTH "${icon_hex}" icon_hex_length)
    math(EXPR icon_byte_length "${icon_hex_length} / 2")
    math(EXPR expected_byte_length "${size} * ${size} * 4")
    if(NOT icon_byte_length EQUAL expected_byte_length)
        message(FATAL_ERROR "embed_window_icon: expected ${expected_byte_length} RGBA bytes, got ${icon_byte_length}")
    endif()

    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," icon_bytes "${icon_hex}")
    string(REGEX REPLACE ",$" "" icon_bytes "${icon_bytes}")

    set(generated_header "${generated_dir}/${symbol}.h")
    file(WRITE "${generated_header}"
"// Generated by cmake/EmbedIcon.cmake from ${jpg}. Do not edit.
#pragma once

namespace slopkit::generated
{

    inline constexpr unsigned char ${symbol}[] = { ${icon_bytes} };

    inline constexpr unsigned long ${symbol}_width = ${size}ul;

    inline constexpr unsigned long ${symbol}_height = ${size}ul;

} // namespace slopkit::generated
")

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${jpg}")

    get_target_property(target_type ${target} TYPE)
    if(target_type STREQUAL "INTERFACE_LIBRARY")
        target_include_directories(${target} INTERFACE "${generated_dir}")
    else()
        target_include_directories(${target} PUBLIC "${generated_dir}")
    endif()
endfunction(embed_window_icon)
